// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cljmgyyyjtythidnpprn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsam1neXl5anR5dGhpZG5wcHJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NjUwNDYsImV4cCI6MjA2MTI0MTA0Nn0.0jC_hyTWa1X4ar0y9aOnOwsfO0gmVp7fTc2cxcjmYu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);